---
# tasks file for roles/postgres-slave

- name: clear out the postgres data dir
  file:
    path: /var/lib/pgsql/data
    state: absent

- name: create the postgres data dir
  file:
    path: /var/lib/pgsql/data
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

# setup replication access for this slave on master in pg_hba.conf
- name: add this slave to pg_hba.conf
  lineinfile:
    line: "host  replication     replication     {{ ansible_all_ipv4_addresses[1] }}/32         md5"
    state: present
    dest: /var/lib/pgsql/data/pg_hba.conf
  delegate_to: "{{ groups.master[0] }}"

- name: restart master
  service:
    name: postgresql
    state: restarted
  delegate_to: "{{ groups.master[0] }}"

- name: suck over the master data
  command: "pg_basebackup -h {{ groups.master[0] }} -D /var/lib/pgsql/data -U replication --xlog-method=stream"
  environment:
    PGPASSWORD: password
  become_user: postgres

- name: install recovery.conf
  template:
    src: recovery.conf.j2
    dest: /var/lib/pgsql/data/recovery.conf
    owner: postgres
    group: postgres

- name: install pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres

- name: install postgres.conf
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
    group: postgres

- name: restart slave
  service:
    name: postgresql
    state: restarted
