---
# tasks file for roles/postgres

- name: install postgresql rpm
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-contrib
    - postgresql-libs
    - python-psycopg2
